server:
  port: 7800
  servlet:
    context-path: /consumer
spring:
  application:
    name: consumer-movie

consumer:
  movie:
    userUrl: http://localhost:7900/provider/user/find/

eureka:
  client:
    com.example.service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}