server:
  port: 8031
  servlet:
    context-path: /hystrix-turbine
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
turbine:
  aggregator:
    cluster-config: CONSUMER-FEIGN-HYSTRIX
  app-config: consumer-feign-hystrix